### PR TITLE
Rename Start.command to Start.sh

### PR DESCRIPTION
**Pull request by skylarr1227**

### CODE REVIEW

**Comment by corpnewt** [comment]
It's currently .command as that's double-click to run on macOS.  With Linux distros, it's not consistent behavior to run a .sh when double clicked - so changing the name doesn't afford any benefit.

-CorpNewt

**Comment by dhinakg** [comment]
Why? Iirc .command allows it to launch with a double click on macOS, so it’s preferable to keep that way. 
Don’t see how changing the extension to .sh would affect it launching on Linux.

**Comment by skylarr1227** [comment]
I didn't mean to even do this guy's, sorry! My daughter had my phone.

**Comment by corpnewt** [comment]
Haha not a problem! It happens :)

**Pull request closed without merging**
