### PR TITLE
Command Issue

### PR DESCRIPTION
**Pull request by DutchAssassin**
Hey there! Sorry, I couldn't find any other way to contact you... I'm still very new to github and it is still very confusing...
Anyway, I seem to have an issue with this part of your code. I merged this with my already existing commands and also added the Settings.py
But every time I try to use this code I get and error (Starting at line 45). I hope you can tell me what I am doing wrong!

(It's about the Broadcast command)

### CODE REVIEW

**Comment by corpnewt** [comment]
The broadcast command doesn't work terribly well since there's no default channels anymore. I could look into it a bit later, but I've left it untouched for some time.

**Comment by DutchAssassin** [comment]
ah, makes sense. Thanks! Would be a cool feature!

another thing I noticed like just now with the TempRole thing. I added a temprole, but when adding to a user I get this error:

  File "C:\Users\niels\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\niels\Downloads\discord_bot.py-master\discord_bot.py-master\cogs\TempRole.py", line 755, in temp
    for r in user_roles:
TypeError: 'NoneType' object is not iterable

**Comment by corpnewt** [comment]
Are you adding in dm? If you run the command in a server, each member at least has the @ everyone role

**Comment by DutchAssassin** [comment]
I use this as the command in my server:

c!temp "@EpicAgentJ#1931" "Rookie" 30s

**Comment by DutchAssassin** [comment]
I noticed my mistake... I didnt mention the role...

**Comment by corpnewt** [comment]
The bot shouldn't need quotes for either the role or the member if they're being mentioned. Also, if you're just typing the name out (CorpNewt instead of @CorpNewt#4290), you only need quotes if there's a space in the name. Glad you were able to get it working!

**Comment by DutchAssassin** [comment]
Oh, that is also very useful to know! Adding those quotes is a pain with mentioning! xD. 

I love your discord bot! I've taken so many commands of it already! I'm already glad I even get them working now. I have no coding experience at all and just copy/paste from open source bots XD. But I think I got most commands from your bot. Damn, you have a lot!

**Comment by corpnewt** [comment]
Just make sure you're crediting the original authors whose commands you use as they're the ones writing and providing them.

**Comment by DutchAssassin** [comment]
oh yes, I will! Everyone who has their discord name added will have their discord name listed too! Just couldnt find yours anywhere :P

**Pull request closed without merging**
